CREATE SCHEMA IF NOT EXISTS ot_springbooth10zf;

CREATE TABLE IF NOT EXISTS ot_springbooth10zf.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  addtime TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ot_springbooth10zf.yonghu (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMPTZ DEFAULT now(),
  yonghuzhanghao TEXT NOT NULL UNIQUE,
  yonghuxingming TEXT NOT NULL,
  mima TEXT NOT NULL,
  xingbie TEXT,
  shouji TEXT,
  touxiang TEXT
);

CREATE TABLE IF NOT EXISTS ot_springbooth10zf.zhongshimeishi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMPTZ DEFAULT now(),
  caipinmingcheng TEXT NOT NULL,
  caixi TEXT,
  tupian TEXT,
  leixing TEXT,
  cailiao TEXT,
  pengrenfangfa TEXT,
  meishideyoulai TEXT,
  pingfen TEXT,
  yonghuzhanghao TEXT,
  yonghuxingming TEXT,
  faburiqi DATE,
  sfsh TEXT,
  shhf TEXT,
  thumbsupnum INTEGER DEFAULT 0,
  crazilynum INTEGER DEFAULT 0,
  clicknum INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ot_springbooth10zf.waiguomeishi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMPTZ DEFAULT now(),
  caipinmingcheng TEXT NOT NULL,
  caixi TEXT,
  tupian TEXT,
  leixing TEXT,
  cailiao TEXT,
  pengrenfangfa TEXT,
  meishideyoulai TEXT,
  pingfen TEXT,
  yonghuzhanghao TEXT,
  yonghuxingming TEXT,
  faburiqi DATE,
  sfsh TEXT,
  shhf TEXT,
  thumbsupnum INTEGER DEFAULT 0,
  crazilynum INTEGER DEFAULT 0,
  clicknum INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ot_springbooth10zf.remencaipin (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMPTZ DEFAULT now(),
  biaoti TEXT NOT NULL,
  fengmian TEXT,
  neirongxiangqing TEXT,
  faburiqi DATE,
  thumbsupnum INTEGER DEFAULT 0,
  crazilynum INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ot_springbooth10zf.news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMPTZ DEFAULT now(),
  title TEXT NOT NULL,
  introduction TEXT,
  picture TEXT,
  content TEXT
);

CREATE TABLE IF NOT EXISTS ot_springbooth10zf.forum (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMPTZ DEFAULT now(),
  title TEXT NOT NULL,
  content TEXT,
  parentid BIGINT DEFAULT 0,
  userid BIGINT,
  username TEXT,
  isdone TEXT DEFAULT '开放'
);

CREATE TABLE IF NOT EXISTS ot_springbooth10zf.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMPTZ DEFAULT now(),
  userid BIGINT,
  username TEXT,
  content TEXT NOT NULL,
  cpicture TEXT,
  reply TEXT,
  rpicture TEXT
);

CREATE TABLE IF NOT EXISTS ot_springbooth10zf.storeup (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMPTZ DEFAULT now(),
  userid BIGINT,
  refid BIGINT,
  tablename TEXT,
  name TEXT,
  picture TEXT,
  type TEXT,
  inteltype TEXT
);

INSERT INTO ot_springbooth10zf.users (id, username, password, role, addtime) VALUES
  (1, 'abo', 'abo', '管理员', '2022-04-09 17:21:55+08')
ON CONFLICT (id) DO UPDATE SET username = EXCLUDED.username, password = EXCLUDED.password, role = EXCLUDED.role;

INSERT INTO ot_springbooth10zf.yonghu (id, addtime, yonghuzhanghao, yonghuxingming, mima, xingbie, shouji, touxiang) VALUES
  (11, '2022-04-09 17:21:55+08', '用户账号1', '用户姓名1', '123456', '男', '13823888881', 'upload/yonghu_touxiang1.jpg'),
  (12, '2022-04-09 17:21:55+08', '用户账号2', '用户姓名2', '123456', '男', '13823888882', 'upload/yonghu_touxiang2.jpg'),
  (13, '2022-04-09 17:21:55+08', '用户账号3', '用户姓名3', '123456', '男', '13823888883', 'upload/yonghu_touxiang3.jpg'),
  (1649496213444, '2022-04-09 17:23:33+08', '11', '李密', '11', '男', '15807550000', NULL)
ON CONFLICT (id) DO UPDATE SET
  yonghuzhanghao = EXCLUDED.yonghuzhanghao,
  yonghuxingming = EXCLUDED.yonghuxingming,
  mima = EXCLUDED.mima,
  xingbie = EXCLUDED.xingbie,
  shouji = EXCLUDED.shouji,
  touxiang = EXCLUDED.touxiang;

INSERT INTO ot_springbooth10zf.zhongshimeishi (id, addtime, caipinmingcheng, caixi, tupian, leixing, cailiao, pengrenfangfa, meishideyoulai, pingfen, yonghuzhanghao, yonghuxingming, faburiqi, sfsh, shhf, thumbsupnum, crazilynum, clicknum) VALUES
  (31, '2022-04-09 17:21:55+08', '葱烧海参', '鲁菜', 'upload/zhongshimeishi_tupian1.jpg', '热菜', '海参、葱、姜', '小火慢煨，收汁入味。', '鲁菜经典宴席菜。', '4.8', '用户账号1', '用户姓名1', '2022-04-09', '是', '', 12, 1, 38),
  (32, '2022-04-09 17:21:55+08', '麻婆豆腐', '川菜', 'upload/zhongshimeishi_tupian2.jpg', '热菜', '豆腐、牛肉末、豆瓣酱', '旺火烧制，麻辣鲜香。', '家常川菜代表。', '4.7', '用户账号2', '用户姓名2', '2022-04-09', '是', '', 20, 2, 52),
  (33, '2022-04-09 17:21:55+08', '西湖牛肉羹', '浙菜', 'upload/zhongshimeishi_tupian3.jpg', '汤羹', '牛肉、蛋清、香菇', '细切慢煮，勾芡成羹。', '江南风味汤羹。', '4.5', '用户账号3', '用户姓名3', '2022-04-09', '是', '', 9, 1, 24)
ON CONFLICT (id) DO UPDATE SET
  caipinmingcheng = EXCLUDED.caipinmingcheng,
  caixi = EXCLUDED.caixi,
  leixing = EXCLUDED.leixing,
  cailiao = EXCLUDED.cailiao,
  pengrenfangfa = EXCLUDED.pengrenfangfa,
  meishideyoulai = EXCLUDED.meishideyoulai,
  pingfen = EXCLUDED.pingfen,
  sfsh = EXCLUDED.sfsh,
  thumbsupnum = EXCLUDED.thumbsupnum,
  crazilynum = EXCLUDED.crazilynum,
  clicknum = EXCLUDED.clicknum;

INSERT INTO ot_springbooth10zf.waiguomeishi (id, addtime, caipinmingcheng, caixi, tupian, leixing, cailiao, pengrenfangfa, meishideyoulai, pingfen, yonghuzhanghao, yonghuxingming, faburiqi, sfsh, shhf, thumbsupnum, crazilynum, clicknum) VALUES
  (21, '2022-04-09 17:21:55+08', '寿司拼盘', '日本料理', 'upload/waiguomeishi_tupian1.jpg', '主食', '米饭、海苔、鱼生', '调味米饭卷制后切件。', '日本代表性料理。', '4.6', '用户账号1', '用户姓名1', '2022-04-09', '是', '', 15, 1, 44),
  (22, '2022-04-09 17:21:55+08', '意式肉酱面', '意大利菜', 'upload/waiguomeishi_tupian2.jpg', '热菜', '意面、番茄、牛肉', '慢熬肉酱后拌面。', '欧洲家庭经典。', '4.5', '用户账号2', '用户姓名2', '2022-04-09', '是', '', 10, 1, 31),
  (23, '2022-04-09 17:21:55+08', '泰式冬阴功汤', '泰国料理', 'upload/waiguomeishi_tupian3.jpg', '汤羹', '虾、香茅、柠檬叶', '酸辣汤底煮海鲜。', '东南亚风味名菜。', '4.4', '用户账号3', '用户姓名3', '2022-04-09', '是', '', 11, 2, 29)
ON CONFLICT (id) DO UPDATE SET
  caipinmingcheng = EXCLUDED.caipinmingcheng,
  caixi = EXCLUDED.caixi,
  leixing = EXCLUDED.leixing,
  cailiao = EXCLUDED.cailiao,
  pengrenfangfa = EXCLUDED.pengrenfangfa,
  meishideyoulai = EXCLUDED.meishideyoulai,
  pingfen = EXCLUDED.pingfen,
  sfsh = EXCLUDED.sfsh,
  thumbsupnum = EXCLUDED.thumbsupnum,
  crazilynum = EXCLUDED.crazilynum,
  clicknum = EXCLUDED.clicknum;

INSERT INTO ot_springbooth10zf.remencaipin (id, addtime, biaoti, fengmian, neirongxiangqing, faburiqi, thumbsupnum, crazilynum) VALUES
  (41, '2022-04-09 17:21:55+08', '本周热门家常菜', 'upload/remencaipin_fengmian1.jpg', '收录适合家庭复刻的高人气菜品。', '2022-04-09', 22, 1),
  (42, '2022-04-09 17:21:55+08', '节日宴客菜单', 'upload/remencaipin_fengmian2.jpg', '整理宴客场景下的组合菜谱。', '2022-04-09', 18, 2),
  (43, '2022-04-09 17:21:55+08', '低脂轻食合集', 'upload/remencaipin_fengmian3.jpg', '面向健康饮食的轻食菜品。', '2022-04-09', 16, 1)
ON CONFLICT (id) DO UPDATE SET
  biaoti = EXCLUDED.biaoti,
  neirongxiangqing = EXCLUDED.neirongxiangqing,
  thumbsupnum = EXCLUDED.thumbsupnum,
  crazilynum = EXCLUDED.crazilynum;

INSERT INTO ot_springbooth10zf.news (id, addtime, title, introduction, picture, content) VALUES
  (71, '2022-04-09 17:21:55+08', '平台发布春季美食专题', '围绕家常菜、地方菜和轻食组合发布专题内容。', 'upload/news_picture1.jpg', '春季美食专题用于展示资讯管理能力。'),
  (72, '2022-04-09 17:21:55+08', '用户菜谱审核流程上线', '管理员可以维护菜品审核状态和回复。', 'upload/news_picture2.jpg', '审核流程用于演示后台管理链路。'),
  (73, '2022-04-09 17:21:55+08', '热门菜品榜单更新', '系统根据点赞、收藏和浏览量展示热门内容。', 'upload/news_picture3.jpg', '榜单用于辅助用户发现菜品。')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, introduction = EXCLUDED.introduction, content = EXCLUDED.content;

INSERT INTO ot_springbooth10zf.forum (id, addtime, title, content, parentid, userid, username, isdone) VALUES
  (51, '2022-04-09 17:21:55+08', '家常菜调味技巧交流', '欢迎分享家常菜调味经验。', 0, 11, '用户账号1', '开放'),
  (52, '2022-04-09 17:21:55+08', '地方菜做法讨论', '讨论各地传统菜的做法差异。', 0, 12, '用户账号2', '开放'),
  (53, '2022-04-09 17:21:55+08', '新手菜谱求推荐', '适合新手的一周菜谱推荐。', 0, 13, '用户账号3', '开放')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, username = EXCLUDED.username, isdone = EXCLUDED.isdone;

INSERT INTO ot_springbooth10zf.messages (id, addtime, userid, username, content, cpicture, reply, rpicture) VALUES
  (81, '2022-04-09 17:21:55+08', 11, '用户账号1', '希望增加更多地方菜分类。', NULL, '已记录，后续会扩展分类。', NULL),
  (82, '2022-04-09 17:21:55+08', 12, '用户账号2', '菜品详情页可以补充步骤图。', NULL, '演示版先保留文本内容。', NULL),
  (83, '2022-04-09 17:21:55+08', 13, '用户账号3', '论坛交流功能很方便。', NULL, '感谢反馈。', NULL)
ON CONFLICT (id) DO UPDATE SET username = EXCLUDED.username, content = EXCLUDED.content, reply = EXCLUDED.reply;

INSERT INTO ot_springbooth10zf.storeup (id, addtime, userid, refid, tablename, name, picture, type, inteltype) VALUES
  (91, '2022-04-09 17:21:55+08', 11, 31, 'zhongshimeishi', '葱烧海参', 'upload/zhongshimeishi_tupian1.jpg', '1', '菜品'),
  (92, '2022-04-09 17:21:55+08', 1649496213444, 21, 'waiguomeishi', '寿司拼盘', 'upload/waiguomeishi_tupian1.jpg', '1', '菜品'),
  (93, '2022-04-09 17:21:55+08', 12, 71, 'news', '平台发布春季美食专题', 'upload/news_picture1.jpg', '1', '资讯')
ON CONFLICT (id) DO UPDATE SET userid = EXCLUDED.userid, refid = EXCLUDED.refid, tablename = EXCLUDED.tablename, name = EXCLUDED.name, type = EXCLUDED.type;

CREATE OR REPLACE FUNCTION public.ot_springbooth10zf_rest(
  p_table_name TEXT,
  p_method TEXT DEFAULT 'GET',
  p_query JSONB DEFAULT '{}'::jsonb,
  p_payload JSONB DEFAULT '{}'::jsonb
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_schema CONSTANT TEXT := 'ot_springbooth10zf';
  v_table TEXT;
  v_sql TEXT;
  v_rows JSONB := '[]'::jsonb;
  v_key TEXT;
  v_value TEXT;
  v_where TEXT := '';
  v_order TEXT := '';
  v_limit TEXT := '';
  v_set TEXT := '';
  v_columns TEXT := '';
  v_values TEXT := '';
BEGIN
  IF p_table_name NOT IN ('users', 'yonghu', 'zhongshimeishi', 'waiguomeishi', 'remencaipin', 'news', 'forum', 'messages', 'storeup') THEN
    RAISE EXCEPTION 'table is not allowed: %', p_table_name;
  END IF;

  v_table := format('%I.%I', v_schema, p_table_name);

  FOR v_key, v_value IN SELECT key, value #>> '{}' FROM jsonb_each(p_query)
  LOOP
    IF v_key = 'select' THEN
      CONTINUE;
    ELSIF v_key = 'order' THEN
      v_order := ' ORDER BY ' || quote_ident(split_part(v_value, '.', 1)) ||
        CASE WHEN lower(split_part(v_value, '.', 2)) = 'desc' THEN ' DESC' ELSE ' ASC' END;
    ELSIF v_key = 'limit' THEN
      v_limit := ' LIMIT ' || LEAST(GREATEST(COALESCE(NULLIF(regexp_replace(v_value, '\D', '', 'g'), '')::INT, 100), 1), 500);
    ELSIF v_value LIKE 'eq.%' THEN
      v_where := v_where || CASE WHEN v_where = '' THEN ' WHERE ' ELSE ' AND ' END ||
        quote_ident(v_key) || ' = ' || quote_literal(substr(v_value, 4));
    ELSIF v_value LIKE 'ilike.%' THEN
      v_where := v_where || CASE WHEN v_where = '' THEN ' WHERE ' ELSE ' AND ' END ||
        quote_ident(v_key) || ' ILIKE ' || quote_literal(replace(substr(v_value, 7), '*', '%'));
    END IF;
  END LOOP;

  IF upper(p_method) = 'GET' THEN
    v_sql := 'SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM (SELECT * FROM ' || v_table || v_where || v_order || v_limit || ') t';
    EXECUTE v_sql INTO v_rows;
    RETURN v_rows;
  ELSIF upper(p_method) = 'POST' THEN
    SELECT string_agg(quote_ident(key), ', '), string_agg(quote_literal(value #>> '{}'), ', ')
    INTO v_columns, v_values
    FROM jsonb_each(p_payload);
    IF v_columns IS NULL THEN
      RAISE EXCEPTION 'payload is empty';
    END IF;
    v_sql := 'WITH changed AS (INSERT INTO ' || v_table || ' (' || v_columns || ') VALUES (' || v_values || ') RETURNING to_jsonb(' || quote_ident(p_table_name) || '.*) AS row) SELECT COALESCE(jsonb_agg(row), ''[]''::jsonb) FROM changed';
    EXECUTE v_sql INTO v_rows;
    RETURN v_rows;
  ELSIF upper(p_method) = 'PATCH' THEN
    SELECT string_agg(quote_ident(key) || ' = ' || quote_literal(value #>> '{}'), ', ')
    INTO v_set
    FROM jsonb_each(p_payload);
    IF v_set IS NULL THEN
      RAISE EXCEPTION 'payload is empty';
    END IF;
    IF v_where = '' THEN
      RAISE EXCEPTION 'patch requires filter';
    END IF;
    v_sql := 'WITH changed AS (UPDATE ' || v_table || ' SET ' || v_set || v_where || ' RETURNING to_jsonb(' || quote_ident(p_table_name) || '.*) AS row) SELECT COALESCE(jsonb_agg(row), ''[]''::jsonb) FROM changed';
    EXECUTE v_sql INTO v_rows;
    RETURN v_rows;
  ELSIF upper(p_method) = 'DELETE' THEN
    IF v_where = '' THEN
      RAISE EXCEPTION 'delete requires filter';
    END IF;
    v_sql := 'WITH changed AS (DELETE FROM ' || v_table || v_where || ' RETURNING to_jsonb(' || quote_ident(p_table_name) || '.*) AS row) SELECT COALESCE(jsonb_agg(row), ''[]''::jsonb) FROM changed';
    EXECUTE v_sql INTO v_rows;
    RETURN v_rows;
  END IF;

  RAISE EXCEPTION 'method is not allowed: %', p_method;
END;
$$;
